name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install cargo-aoc
      run: cargo install cargo-aoc
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
